spring.application.name=maxx-dental-backend
spring.profiles.include=mail

# Correct console log pattern
logging.pattern.console=Timestamp=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} | Severity=%clr(%-5p){green} | MicroService=%clr(${spring.application.name}){yellow} | Message=%m%n

frontend.server.url=http://localhost:3000